version: "3.7"
services:
  dev_db:
    image: postgres:9.6.17-alpine
    container_name: dev_db
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: shop
      POSTGRES_INITDB_ARGS: --data-checksums
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - 5432:5432
