version: "3.7"
services:

  dev_db:
    image: postgres:9.6-alpine
    container_name: dev_db
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: shop
      POSTGRES_INITDB_ARGS: --data-checksums
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - ./setup-test-data.sql:/docker-entrypoint-initdb.d/setup-test-data.sql
